name: Multiverse-CommandDestination
description: ${project.description}
version: ${project.version}
main: dev.benergy10.multiversecommanddestination.MultiverseCommandDestination
api-version: 1.13
authors: [ benwoo1110 ]
depend: [Multiverse-Core]
softdepend: [Multiverse-Portals, PlaceholderAPI]
